"""add booking and slot constraints

Revision ID: 684713234bbe
Revises: 1e8819f3ef02
Create Date: 2026-06-06 21:23:10.468012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '684713234bbe'
down_revision: Union[str, Sequence[str], None] = '1e8819f3ef02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookings_id'), table_name='bookings')
    op.create_index(op.f('ix_bookings_booking_date'), 'bookings', ['booking_date'], unique=False)
    op.drop_constraint(op.f('bookings_room_id_fkey'), 'bookings', type_='foreignkey')
    op.drop_constraint(op.f('bookings_time_slot_id_fkey'), 'bookings', type_='foreignkey')
    op.create_foreign_key(None, 'bookings', 'time_slots', ['time_slot_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'bookings', 'rooms.csv', ['room_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_rooms_id'), table_name='rooms.csv')
    op.drop_index(op.f('ix_time_slots_id'), table_name='time_slots')
    op.create_unique_constraint('uq_room_time_slot', 'time_slots', ['room_id', 'start_time', 'end_time'])
    op.drop_constraint(op.f('time_slots_room_id_fkey'), 'time_slots', type_='foreignkey')
    op.create_foreign_key(None, 'time_slots', 'rooms.csv', ['room_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_constraint(None, 'time_slots', type_='foreignkey')
    op.create_foreign_key(op.f('time_slots_room_id_fkey'), 'time_slots', 'rooms.csv', ['room_id'], ['id'])
    op.drop_constraint('uq_room_time_slot', 'time_slots', type_='unique')
    op.create_index(op.f('ix_time_slots_id'), 'time_slots', ['id'], unique=False)
    op.create_index(op.f('ix_rooms_id'), 'rooms.csv', ['id'], unique=False)
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.create_foreign_key(op.f('bookings_time_slot_id_fkey'), 'bookings', 'time_slots', ['time_slot_id'], ['id'])
    op.create_foreign_key(op.f('bookings_room_id_fkey'), 'bookings', 'rooms.csv', ['room_id'], ['id'])
    op.drop_index(op.f('ix_bookings_booking_date'), table_name='bookings')
    op.create_index(op.f('ix_bookings_id'), 'bookings', ['id'], unique=False)
    # ### end Alembic commands ###
